### ISSUE TITLE
Rename 'rate' to 'percentage'

### ISSUE THREAD

**Issue by calisaurus** [connected-web/boardgames-api#10]
Currently person win percentages are shown as:

```
winRateHannah: 0.4545,
winRateJohn: 0.5,
winRateOther: 0.0455,
winRateDraw: 0,
```

This should be renamed to `winPercentage<name>` to be consistent with `coOpGamesPlayedPercentage` and new data as proposed in https://github.com/connected-web/boardgames-api/issues/9#issue-626980022

**Comment by calisaurus** [comment]
If this work is done, refactoring will need to be done in https://github.com/calisaurus/calisaurus-boardgames/tree/master/content/html/quick-looks/2020 to ensure the correct display of data.

**Comment by johnbeech** [comment]
Done
