### ISSUE TITLE
Challenge grid: Map any non-matching games to 'Wildcard'

### ISSUE THREAD

**Issue by calisaurus** [connected-web/boardgames-api#41]
As a category in 2021, we are tracking 'wildcard' games, which should also be logged against the overall (and by card: wildcard) completion percentages.

For example:
- 'Mandala' should be mapped to wildcard 
- '7 Wonders Duel' should be mapped to 'Wildcard' NOT '7 Wonders'
- 'Pandemic: Contagion' / 'Pandemic: The Cure' / 'Pandemic: Rapid Response' should be mapped to 'Wildcard' NOT - 'Pandemic'
- 'Ticket to Ride Map Collection: Volume 6 – France & Old West' should be matched to 'Ticket to Ride'

**Comment by johnbeech** [comment]
I'm making the assumption that the "Game Family" column in the source sheet will be filled out - and any mention of "wildcard" or empty ("") will map to wildcard. Any other family will perform a lookup in the list of 20 challenge Game Family coded elsewhere; e.g. Tab 1 (20x21) in Board Games 2021

**Comment by johnbeech** [comment]
Note to self; this is the current check (which needs updating), because it would incorrectly map games as it has a soft check (using `includes()`) instead of checking for exact equality:
```js
(game.gameFamily === gameFamily || game.name.includes(gameFamily))
```
