### ISSUE TITLE
Map individual games to their parent game

### ISSUE THREAD

**Issue by calisaurus** [connected-web/boardgames-api#42]
Opposite of #41 

For example:
- 'Ticket to Ride Map Collection: Volume 6 – France & Old West' | 'Ticket to Ride France' should match to Ticket to Ride
- 'Letters to Santa' should match to 'Love Letter'

Complete list TBD

**Comment by johnbeech** [comment]
Done, see:
- https://boardgames-api.calisaurus.net/api/boardgame/grids/byYear/2018 (3x5 grid)
- https://boardgames-api.calisaurus.net/api/boardgame/grids/byYear/2019 (empty grid)
- https://boardgames-api.calisaurus.net/api/boardgame/grids/byYear/2020 (3x10 grid)
- https://boardgames-api.calisaurus.net/api/boardgame/grids/byYear/2021 (21x20 grid)

**Comment by johnbeech** [comment]
Note: overall stats haven't been calculated yet - still need to do that... new ticket. Should be obvious before long.
