### ISSUE TITLE
Expand gameFamilies to include all 20 selected game families

### ISSUE THREAD

**Issue by calisaurus** [connected-web/boardgames-api#53]
`gameFamilies: [
"Pandemic",
"Love Letter",
"Dominion"
],` 

should include:

Flotsam Fight
Jurassic Snack
Love Letter
Mint Works
Corsairs of Valeria
Deep Sea Adventure
Lovecraft Letter
Design Town
Topiary
Dominion
7 Wonders
Star Realms
Pandemic
Tanto Cuore
Ticket to Ride
Valeria Card Kingdoms
Aeon's End
Wingspan
Brass
Scythe

**Comment by johnbeech** [comment]
Updated 2018 and 2020 challenges; also set the expected games to play to be 20 to make more sensible percentages as an estimate of 2021 based on previous years.

See:
- https://boardgames-api.calisaurus.net/api/boardgame/grids/byYear/2018
- https://boardgames-api.calisaurus.net/api/boardgame/grids/byYear/2020
