### ISSUE TITLE
Feature request: endpoint for game by year/month

### ISSUE THREAD

**Issue by calisaurus** [connected-web/boardgames-api#73]
I want to return a list of plays of a specific game by year, and by month.

For example: I want to see how many times Love Letter was played in 2021 / I want to see how many times Jurassic Snack was played in July 2020.

**Comment by johnbeech** [comment]
Thought: could this be done in the boardgame browser? For example by grouping the list by year, and adding a summary count? Might be worth doing in both places.

**Comment by johnbeech** [comment]
Here's the commit for a change to the boardgames browser to filter play records by year:
- https://github.com/connected-web/boardgames-browser/commit/d2a71983060e43a5ef1e1f3879db44e148085a1a|

And some interactive links:, e.g.
- "[How many times Love Letter was played in 2021 (by Tag)?](https://connected-web.github.io/boardgames-browser/tags/byValue/?tag=gameFamily&value=love-letter)" Answer: 32
- "[How many times Love Letter was played in 2021 (by Game ID)?](https://connected-web.github.io/boardgames-browser/game/?game=love-letter)" Answer: 4
- "[How many times Jurassic Snack was played in July 2020](https://connected-web.github.io/boardgames-browser/game/?game=jurassic-snack)" Answer: 0

The problem with trying to answer this question via the Boardgames API is that the current method of pre-generating datasets based on categories (years, months, grids, game IDs, tags) doesn't divide well down into smaller endpoints without a redesign of the server and/or writing a lot more PHP code. It can be done, I just don't know if its worth it.
